// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPrmnOo-X6rJg4G4sYNfvsOcZ2vO19ECg',
    appId: '1:120666422320:web:cb43c735514f75b470c1f5',
    messagingSenderId: '120666422320',
    projectId: 'project-mobile-app-3154a',
    authDomain: 'project-mobile-app-3154a.firebaseapp.com',
    storageBucket: 'project-mobile-app-3154a.appspot.com',
    measurementId: 'G-RBB8TG8KQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFimaeWzAxKUTlDIQ3FDEs621jLRBsypg',
    appId: '1:120666422320:android:c259dd27d0e4999670c1f5',
    messagingSenderId: '120666422320',
    projectId: 'project-mobile-app-3154a',
    storageBucket: 'project-mobile-app-3154a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAyztJPjWPbqVTMb5tqmpkw4bJBUT6aYo',
    appId: '1:120666422320:ios:f6a8386ce7efc7db70c1f5',
    messagingSenderId: '120666422320',
    projectId: 'project-mobile-app-3154a',
    storageBucket: 'project-mobile-app-3154a.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAyztJPjWPbqVTMb5tqmpkw4bJBUT6aYo',
    appId: '1:120666422320:ios:f6a8386ce7efc7db70c1f5',
    messagingSenderId: '120666422320',
    projectId: 'project-mobile-app-3154a',
    storageBucket: 'project-mobile-app-3154a.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPrmnOo-X6rJg4G4sYNfvsOcZ2vO19ECg',
    appId: '1:120666422320:web:5cc29b9215339d0070c1f5',
    messagingSenderId: '120666422320',
    projectId: 'project-mobile-app-3154a',
    authDomain: 'project-mobile-app-3154a.firebaseapp.com',
    storageBucket: 'project-mobile-app-3154a.appspot.com',
    measurementId: 'G-9GWQXN1YQD',
  );
}
